examples/upload-download-files-oauth2-rails-api/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :downloads, only: %i[new create]
  resources :uploads, only: %i[new create]

  resources :oauth2_flows, only: %i[new] do
    collection do
      get 'callback'
      get 'log_out'
    end
  end

  resources :projects, only: %i[index] do
    collection do
      post 'choose'
    end
  end

  root 'oauth2_flows#new'
end

examples/upload-download-files-oauth2-rails-api/app/models/import.rb
# frozen_string_literal: true

class Import < ApplicationRecord
end

examples/upload-download-files-oauth2-rails-api/app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
end

examples/upload-download-files-oauth2-rails-api/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def check_token
    redirect_to new_oauth2_flow_path unless session[:lokalise_token].present?
  end

  def check_project_id
    redirect_to new_oauth2_flow_path unless session[:lokalise_project_id].present?
  end
end

examples/upload-download-files-oauth2-rails-api/app/controllers/downloads_controller.rb
# frozen_string_literal: true

require 'ruby_lokalise_api'
require 'open-uri'
require 'zip'

class DownloadsController < ApplicationController
  before_action :check_token
  before_action :check_project_id

  def new; end

  def create
    client = RubyLokaliseApi.oauth2_client session[:lokalise_token] # .client ENV['LOKALISE_API_KEY']

    zip_file = client.download_files(session[:lokalise_project_id], # ENV['LOKALISE_PROJECT_ID'],
                                     format: 'yaml',
                                     placeholder_format: :icu,
                                     yaml_include_root: true,
                                     original_filenames: true,
                                     directory_prefix: '',
                                     indentation: '2sp',
                                     filter_langs: %w[en])['bundle_url']

    open_and_process zip_file

    redirect_to new_download_path
  end

  private

  def open_and_process(path)
    Zip::File.open_buffer(open_remote(path)) do |zip|
      zip.each do |entry|
        next unless entry.name == 'en.yml'

        process_zip(entry)
      end
    end
  end

  def open_remote(path)
    parsed_path = URI.parse(path)
    parsed_path.open
  end

  def process_zip(entry)
    data = YAML.safe_load(entry.get_input_stream.read)

    File.open(File.join(Rails.root, 'config', 'locales', entry.name), 'w+:UTF-8') do |f|
      f.write data.to_yaml
    end
  end
end

examples/upload-download-files-oauth2-rails-api/app/controllers/oauth2_flows_controller.rb
# frozen_string_literal: true

require 'ruby_lokalise_api'

class Oauth2FlowsController < ApplicationController
  def new
    @auth_url = auth_client.auth scope: %(read_projects read_files write_files),
                                 redirect_uri: 'http://localhost:3000/oauth2_flows/callback',
                                 state: rand(10_000)
  end

  def callback
    response = auth_client.token params[:code]
    session[:lokalise_token] = response.access_token
    session[:lokalise_refresh] = response.refresh_token

    redirect_to new_oauth2_flow_path
  end

  def log_out
    session.delete :lokalise_token
    session.delete :lokalise_refresh
    session.delete :lokalise_project_id
    redirect_to new_oauth2_flow_path
  end

  private

  def auth_client
    RubyLokaliseApi.auth_client ENV['OAUTH2_CLIENT_ID'], ENV['OAUTH2_CLIENT_SECRET']
  end
end

examples/upload-download-files-oauth2-rails-api/app/controllers/projects_controller.rb
# frozen_string_literal: true

require 'ruby_lokalise_api'

class ProjectsController < ApplicationController
  before_action :check_token

  def index
    client = RubyLokaliseApi.oauth2_client session[:lokalise_token]
    @projects = client.projects(limit: 5000).collection.map { |p| { id: p.project_id, name: p.name } }
  end

  def choose
    session[:lokalise_project_id] = params[:project_id]
    redirect_to new_oauth2_flow_path
  end
end

examples/upload-download-files-oauth2-rails-api/app/controllers/uploads_controller.rb
# frozen_string_literal: true

require 'ruby_lokalise_api'

class UploadsController < ApplicationController
  before_action :check_token
  before_action :check_project_id

  def new; end

  def create
    client = RubyLokaliseApi.oauth2_client session[:lokalise_token]
    # client = RubyLokaliseApi.client ENV['LOKALISE_API_KEY']

    file_content = File.read "#{Rails.root}/config/locales/en.yml"

    client.upload_file session[:lokalise_project_id], #ENV['LOKALISE_PROJECT_ID'],
                       data: Base64.strict_encode64(file_content.strip),
                       filename: 'en.yml',
                       lang_iso: 'en'

    redirect_to new_upload_path
  end
end

examples/upload-download-files-oauth2-rails-api/app/helpers/downloads_helper.rb
# frozen_string_literal: true

module DownloadsHelper
end

examples/upload-download-files-oauth2-rails-api/app/helpers/imports_helper.rb
# frozen_string_literal: true

module ImportsHelper
end

examples/upload-download-files-oauth2-rails-api/app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

examples/upload-download-files-oauth2-rails-api/app/helpers/uploads_helper.rb
# frozen_string_literal: true

module UploadsHelper
end

examples/upload-download-files-oauth2-rails-api/app/views/downloads/new.html.erb
<h1><%= t 'download_title' %></h1>

<%= button_to t('download_btn'), downloads_path %>

examples/upload-download-files-oauth2-rails-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LokaliseApiDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

examples/upload-download-files-oauth2-rails-api/app/views/oauth2_flows/new.html.erb
<h1>OAuth 2 flow</h1>

<% if session[:lokalise_token].present? %>
  Your OAuth 2 token: <%= session[:lokalise_token] %><br>
  Your OAuth 2 refresh token: <%= session[:lokalise_refresh] %><br>
  Your Lokalise project id: <%= session[:lokalise_project_id] %><br>

  <%= link_to 'Choose a project to work with', projects_path %><br>
  <%= link_to 'Upload file', new_upload_path %><br>
  <%= link_to 'Download file', new_download_path %><br><br>
  <%= link_to 'Log out', log_out_oauth2_flows_path %>
<% else %>
  <%= link_to 'Log in via Lokalise', @auth_url %>
<% end %>

examples/upload-download-files-oauth2-rails-api/app/views/projects/index.html.erb
<h1>Choose a project to work with</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= button_to project[:name], choose_projects_path(project_id: project[:id]) %>
      ID: <%= project[:id] %>
      <% if session[:lokalise_project_id] == project[:id] %>
        (currently chosen)
      <% end %>
    </li>
  <% end %>
</ul>