examples/webhooks-rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :webhooks, only: %i[new create] do
    collection do
      post 'notify'
    end
  end

  root 'webhooks#new'
end

examples/webhooks-rails/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

examples/webhooks-rails/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

examples/webhooks-rails/app/controllers/webhooks_controller.rb
# frozen_string_literal: true

require 'ruby_lokalise_api'

class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:notify]

  def new; end

  def create
    api_client.create_webhook params[:project_id],
                              url: 'https://lokalise-webhooks-rails.herokuapp.com/webhooks/notify',
                              events: %w[project.key.added]

    redirect_to root_path
  end

  def notify
    if params[:event] == 'project.key.added'
      project_id = params[:project][:id]
      key_id = params[:key][:id]

      api_client.create_comments project_id, key_id, [
        { comment: '@Bob could you please double check this key to make sure it complies with our requirements?' }
      ]

      api_client.update_key project_id, key_id, is_hidden: true
    end
    
    if params[:event] == 'project.translations.updated'
      puts "Project name: #{params[:project][:name]}"
      puts "User name: #{params[:user][:full_name]}"

      params[:translations].each do |translation|
        puts "Translation ID: #{translation[:id]}"
        puts "Translation value: #{translation[:value]}"
        puts "Language: #{translation[:language][:name]}"
        puts "Key: #{translation[:key][:name]}"
      end
    end

    head :ok
  end

  private

  def api_client
    @client ||= RubyLokaliseApi.client ENV['LOKALISE_API_TOKEN']
  end
end

examples/webhooks-rails/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

examples/webhooks-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LokaliseWebhooksDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

examples/webhooks-rails/app/views/webhooks/new.html.erb
<h1>Register a new webhook</h1>

<%= form_with url: webhooks_path do |f| %>
  <%= f.label :project_id %>
  <%= f.text_field :project_id %>
  <%= f.submit "Register!" %>
<% end %>